### ISSUE TITLE
Error: Linking globals named 'sha256_transform': symbol multiply defined!

### ISSUE THREAD

**Issue by michaldrabik** [ttypic/kmm-embedded-c#1]
Hi @ttypic 

Was trying to complete your tutorial on adding C code into KMP project but I'm hitting a bump.
Basically after setting everything up I'm able to run Android app without problem and it works fine with JNI etc.

However with iOS I'm constantly getting following error while trying to run the app:

```
> Task :shared:cinteropSha256IosSimulatorArm64 UP-TO-DATE
> Task :shared:iosSimulatorArm64Sha256 UP-TO-DATE
> Task :shared:compileKotlinIosSimulatorArm64 UP-TO-DATE

> Task :shared:linkDebugFrameworkIosSimulatorArm64 FAILED
error: Compilation failed: Linking globals named 'sha256_transform': symbol multiply defined!

 * Source files: 
 * Compiler version: 1.9.10
 * Output kind: FRAMEWORK

error: java.lang.Error: Linking globals named 'sha256_transform': symbol multiply defined!
	at org.jetbrains.kotlin.backend.konan.llvm.DefaultLlvmDiagnosticHandler.handle(diagnosticReport.kt:25)
	at org.jetbrains.kotlin.backend.konan.llvm.LlvmDiagnosticCollector.flush(diagnostics.kt:36)
	at org.jetbrains.kotlin.backend.konan.llvm.LinkModulesKt.llvmLinkModules2(linkModules.kt:37)
	at org.jetbrains.kotlin.backend.konan.CompilerOutputKt.linkAllDependencies(CompilerOutput.kt:129)
	at org.jetbrains.kotlin.backend.konan.CompilerOutputKt.linkBitcodeDependencies(CompilerOutput.kt:155)

...

```

I'm wondering If you might have any guidance on what might be happening here on the iOS side. Thanks.

**Comment by ttypic** [comment]
Hi @michaldrabik ! Could you share Xcode version? If you are using Xcode < 15 could you try to use Kotlin 1.7.20 instead of 1.9.10? CKlib plugin that is using to compile C code for iOS platform uses some hacks to do this and probably they are not agreeing with the newest kotlin native compiler. I will take a look later

**Comment by michaldrabik** [comment]
Thanks. 

XCode Version 15.0 (15A240d)

Also to clarify. Your project only consists of KMP Library. The apps have been added using this guide: https://kotlinlang.org/docs/multiplatform-mobile-integrate-in-existing-app.html

**Comment by abdelrhmanelgendy** [comment]
@michaldrabik 

Hello dear, I am facing the same issue while assemble a xcframework..

Did you reach any solution or a workaround ?
